[package]
name = "my_lib"
version = "0.1.0"
edition = "2021"

[dependencies]
shared = { path = "../../shared" }
serde = { workspace = true }
serde_json = { workspace = true }
anyhow = { workspace = true }

[dev-dependencies]
criterion = { workspace = true }
